name: Android CI with SonarCloud

on:
  push:
    branches: [ main ]  # Ensure this matches your SonarCloud default branch
  pull_request:
    branches: [ main ]  

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensures full history for SonarCloud PR analysis

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant Execute Permission for Gradle
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --stacktrace

    - name: Run SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        SONAR_TOKEN: ${{ secrets.MYREBONNTE_SONARCLOUD_TOKEN }}  
      run: |
        ./gradlew sonar \
          -Dsonar.token=$SONAR_TOKEN \
          -Dsonar.projectKey=BriceUlrichAfferi_Rebonnte \
          -Dsonar.organization=briceulrichafferi \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.branch.name=main
