name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: self-hosted  # Assuming self-hosted runner with Android device connected

    env:
      ANDROID_HOME: C:\Users\commu\AppData\Local\Android\Sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK Tools
        run: |
          $env:Path += ";C:\Users\commu\AppData\Local\Android\Sdk\platform-tools"
          adb devices

      - name: Write Keystore File
        shell: powershell
        run: |
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.KEYSTORE_FILE }}")) | Out-File -FilePath "mykeystore.jks" -Encoding UTF8

      - name: Write Keystore Properties
        shell: powershell
        run: |
          @"
          storeFile=${{ github.workspace }}\mykeystore.jks
          storePassword=${{ secrets.STORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          "@ | Out-File -FilePath "keystore.properties" -Encoding UTF8

      - name: Build Release APK
        run: .\gradlew.bat assembleRelease --stacktrace

      - name: Run Unit Tests (Optional)
        if: success()  # Only run if build succeeds
        run: |
          .\gradlew.bat testDebugUnitTest --stacktrace --continue
        continue-on-error: true  # Allow workflow to proceed even if tests fail

      - name: Run Instrumented Tests on Real Device (Optional)
        if: success()  # Only run if build succeeds
        run: |
          adb devices
          # Optional: Disconnect emulator if present
          adb -s emulator-5554 emu kill || Write-Host "No emulator to kill"
          # Verify real device
          adb -s 1cc072ab2f090dre shell pm list packages
          .\gradlew.bat connectedAndroidTest --stacktrace --continue
        continue-on-error: true  # Allow workflow to proceed even if tests fail

      - name: Upload Test Results
        if: always()  # Upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/test-results/**/*.html

      - name: Upload APK
        if: always()  # Upload APK even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk