name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # Your self-hosted Windows runner

    env:
      ANDROID_HOME: C:\Users\commu\AppData\Local\Android\Sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Write Keystore File
        shell: powershell
        run: |
          [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.KEYSTORE_FILE }}")) | Out-File -FilePath "new_keystore.jks" -Encoding UTF8

      - name: Write Keystore Properties
        shell: powershell
        run: |
          @"
          storeFile=${{ github.workspace }}\new_keystore.jks
          storePassword=${{ secrets.STORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          "@ | Out-File -FilePath "keystore.properties" -Encoding UTF8

      - name: Verify Keystore Setup (Debug)
        shell: powershell
        run: |
          if (Test-Path "new_keystore.jks") { Write-Host "Keystore file exists" } else { Write-Host "Keystore file missing" }
          Get-Content "keystore.properties" || Write-Host "Failed to read keystore.properties"

      - name: Build Release APK
        run: .\gradlew.bat assembleRelease --stacktrace

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk