name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    env:
      ANDROID_HOME: C:\Users\commu\AppData\Local\Android\Sdk  # Adjust if your SDK is elsewhere

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: |
          # Ensure gradlew.bat is executable
          if (Test-Path ./gradlew.bat) { ./gradlew.bat build } else { ./gradlew build }

      - name: Run Instrumented Tests on Real Device
        run: |
          adb devices
          # Replace with the actual device ID
          ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.device=1cc072ab2f037ece --stacktrace

      - name: Upload Test Results
        if: always() # Runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/test-results/**/*.html