name: Firebase Distribution

on:
  push:

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace # Added --stacktrace for better debugging

      - name: Verify APK Path
        run: ls -la app/build/outputs/apk/release # Corrected path

      # Debugging Firebase credentials to check if the secret is set correctly
      - name: Debugging Firebase credentials
        run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > eventoriassignin-firebase-adminsdk-fbsvc-685e429f94.json
        shell: bash

      # Check if the Firebase credentials file was written correctly
      - name: Check Firebase credentials file
        run: cat eventoriassignin-firebase-adminsdk-fbsvc-685e429f94.json # Fixed filename to match previous step

      # Upload the APK to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: "testers"
          file: "app/build/outputs/apk/release/app-release.apk" # Already correct
          releaseNotes: "Automated release from GitHub Actions"
          debug: true
