name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: self-hosted

    env:
      ANDROID_HOME: C:\Users\commu\AppData\Local\Android\Sdk

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK Tools
        run: |
          $env:Path += ";C:\Users\commu\AppData\Local\Android\Sdk\platform-tools"
          adb devices

      - name: Write keystore.properties
        run: |
          echo "storeFile=app/new_keystore.jks" > keystore.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties

      - name: Write keystore file
        run: |
          # Decode the base64 encoded keystore string and write it as a binary file
          [System.IO.File]::WriteAllBytes("app/new_keystore.jks", [System.Convert]::FromBase64String("${{ secrets.KEYSTORE_FILE }}"))
      
      

      - name: Verify keystore files (debug)
        run: |
          dir keystore.properties
          dir app\new_keystore.jks

      - name: Build with Gradle (Debug and Release)
        run: .\gradlew.bat build -x lint --stacktrace

      - name: Run Unit Tests
        run: |
          .\gradlew.bat testDebugUnitTest --stacktrace

      - name: Run Instrumented Tests on Real Device
        run: |
          adb devices
          # Optional: Disconnect emulator to ensure only real device is used
          adb -s emulator-5554 emu kill
          if ($?) { Write-Host "Emulator killed successfully" } else { Write-Host "Failed to kill emulator or no emulator found" }
          # Verify real device is active
          adb -s 1cc072ab2f090dre shell pm list packages
          .\gradlew.bat connectedAndroidTest --stacktrace

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/build/test-results/**/*.html

      - name: Upload Release APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk